[tool.poetry]
name = "PavelGoshurenko_getdiff"
version = "0.1.0"
description = ""
authors = ["Pavel Goshurenko <goshurenkopl@gmail.com>"]

packages = [
  { include = "gendiff" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
gendiff = "gendiff.scripts.gendiff:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
